apiVersion: apps/v1
kind: Deployment
metadata:
  name: project01
  labels:
    type: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web
    spec:
      containers:
      - name: web-server
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
        - containerPort: 443

